apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
  # # inject jaeger as a sidecar
  # annotations:
  #   "sidecar.jaegertracing.io/inject": "true"
spec:
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google-samples/gb-frontend:v4
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env

        # - name: JAEGER_SERVICE_NAME
        #   value: aeger-agent
        # - name: JAEGER_AGENT_HOST
        #   value: my-jaeger-agent
        # - name: JAEGER_SAMPLER_TYPE
        #   value: const
        # - name: JAEGER_SAMPLER_PARAM
        #   value: "1"

        ports:
        - containerPort: 80

      # - name: jaeger-agent
      #   image: jaegertracing/jaeger-agent
      #   ports:
      #   - containerPort: 5775
      #     protocol: UDP
      #   - containerPort: 6831
      #     protocol: UDP
      #   - containerPort: 6832
      #     protocol: UDP
      #   - containerPort: 5778
      #     protocol: TCP
      #   args: ["--collector.host-port=jaeger-collector.jaeger-infra.svc:14267"]
